### PR TITLE
Pin dependencies and fix retrieve function

### PR DESCRIPTION
**Pull request by benf2004**
The game crashing is fixed by pinning the dependencies to older versions. The retrieve function was not working, and I have updated it to work.

### CODE REVIEW

**Comment by benf2004** [comment]
fixes #16

**Comment by stuartthomas25** [comment]
Awesome, thanks. Sorry I've been doing my real job recently and haven't been able to pay as much attention to JParty.

**Comment by jordan109** [comment]
Stuartthomas how do you get jparty to work on my windows I need help and I don't know how to install it right could you at least make a video or do something

**Comment by stuartthomas25** [comment]
I can't really make a video right now but you should just be able to download the ["JParty.exe"](https://github.com/stuartthomas25/JParty/releases/download/v2.0.1/JParty.exe) file from the Releases page. Don't worry about extracting the source files.

**Comment by jordan109** [comment]
I just downloaded it and every time I type in a game a random game it says cannot get game how do you fix that

**Comment by jordan109** [comment]
It's like I don't know what to do when I hit random button nothing comes up

**Comment by jordan109** [comment]
And then with the buzzer when I scan it and then try to open the link the buzzer on my phone it's not working

**Comment by jordan109** [comment]
Stuartthomas downloaded it and every time I type in a game a random game it says cannot get game how do you fix that It's like I don't know what to do when I hit random button nothing comes up And then with the buzzer when I scan it and then try to open the link the buzzer on my phone it's not working

**Comment by jordan109** [comment]
Here is proof

**Comment by jordan109** [comment]
How do I do that for wayback machine can you send me the link or how do I comply it and if I do which do I comply what is the name of it in the file

**Comment by benf2004** [comment]
@jordan109 I was able to compile the Windows version but I couldn't test it. Here is [the link to download it - Jparty.exe](https://github.com/benf2004/JParty/releases/tag/v2.0.2-windows). Would you test it out and let me know if it works?

**Comment by jordan109** [comment]
hello benf2004 i just got finished downloading it and now it is working but i have to get a little further more and test it more to see what is working good and what still needs improvement  i will keep you updated as i test further thank you so much though as a gift for helping me i gotta say your smart celver and sweet ❤️👌

**Comment by jordan109** [comment]
i also have more questions   how colud i use this without moniotor or tv colud i plug my laptop in  using a anthor laptop a windows tablet or a smartphone and i do i inmport the jeopardy 2021 set and use the grapichs like the daily double blue sky background and other jeopardy images from the show using the seasons 1-39 images also like round 1 jeopardy double and final jeopardy and use catergorgy images  and ones with sound to

**Pull request merged**
